language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk7

env:
  - BUILD=build

matrix:
  fast_finish: true

install:
  - if [[ $BUILD == 'build' ]]; then mvn install; fi
