language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk7

env:
  - BUILD=maven_findbugs
  - BUILD=maven

matrix:
  fast_finish: true

install:
  - if [[ $BUILD == 'maven' ]]; then mvn install; fi
  - if [[ $BUILD == 'maven_findbugs' ]]; then mvn findbugs:findbugs -Dfindbugs.threshold=medium; fi

matrix:
  exclude:
    - jdk: openjdk7
      env: BUILD=maven_findbugs
